# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: bionic
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    - WARNINGS_OK=false
    - ROS_REPO=ros

jobs:
  fast_finish: true
  include:
    - env: TEST="clang-format ament_lint" ROS_DISTRO=foxy
    - env: ROS_DISTRO=foxy

before_script:
  - git clone -q -b ros2 --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh
