# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: BuildAndTest

# This determines when this workflow is run
on:
  # When kinetic-devel branch is pushed to
  push:
    branches: [ kinetic-devel ]
  # When there is a pull request against kinetic-devel
  pull_request:
    branches: [ kinetic-devel ]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic, ROS_REPO: main}
          - {ROS_DISTRO: kinetic, ROS_REPO: testing}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
