# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: BuildAndTest

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: foxy, ROS_REPO: main}
          - {ROS_DISTRO: foxy, ROS_REPO: testing}
    env:
      CCACHE_DIR: '$HOME/.ccache'
      AFTER_BUILD_TARGET_WORKSPACE: 'ccache -s'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ccache
        run: sudo apt -qq install ccache
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ github.sha }}  
          restore-keys: |
            ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      - name: ccache stats
        run: ccache -s
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
      - name: ccache stats
        run: ccache -s
